CREATE TABLE IF NOT EXISTS ARTICLES (
	ARTICLE_ID  BIGSERIAL PRIMARY KEY, 
	URL CHAR(500) NOT NULL,
	AUTHOR CHAR(100),
	TITLE CHAR(500),
	POST_BODY TEXT,
	TOP_IMAGE_URL CHAR(500),
	IMAGE_URLS CHAR(500)[],
	TAGS CHAR(50)[],
	POST_SUMMARY CHAR(2000),
	LIKE_COUNT INTEGER DEFAULT 0,
	BLOG_ID INTEGER,
	PUBLISH_DATE TIMESTAMP with time zone
);
CREATE UNIQUE INDEX url_idx ON Articles (url);

CREATE TABLE IF NOT EXISTS BLOGS (
	BLOG_ID  SERIAL PRIMARY KEY, 
	NAME CHAR(50)
	URL CHAR(500) NOT NULL,
	IS_ACTIVE BOOLEAN
);